In [1]:
import pandas as pd

In [26]:
df = pd.read_csv("./small_set/GPSS1.CSV", header=None, encoding="big5")

In [27]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,ANN-6280,90,0,126,↘,50,219184,2665520,120.6969,24.0944,,2018-01-24 11:16:22,336036,0.0,50,400600
1,ANN-6280,90,0,126,↘,50,219184,2665520,120.6969,24.0944,,2018-01-24 11:16:52,336036,0.0,50,400600
2,ANN-6280,90,0,126,↘,50,219184,2665520,120.6969,24.0944,,2018-01-24 11:17:22,336036,0.0,50,400600
3,ANN-6280,90,0,126,↘,50,219174,2665520,120.6968,24.0944,,2018-01-24 11:17:52,358541,10.0,50,400600
4,ANN-6280,90,0,126,↘,50,219174,2665520,120.6968,24.0944,,2018-01-24 11:18:22,358541,0.0,50,400600
5,ANN-6280,90,0,126,↘,50,219174,2665520,120.6968,24.0944,,2018-01-24 11:18:52,358541,0.0,50,400600
6,ANN-6280,90,0,126,↘,50,219184,2665520,120.6969,24.0944,,2018-01-24 11:19:22,336036,10.0,50,400600
7,ANN-6280,0,32,129,↘,50,219245,2665475,120.6975,24.0940,,2018-01-24 11:19:52,336036,76.0,50,400600
8,ANN-6280,90,0,19,↗,50,219316,2665508,120.6982,24.0943,,2018-01-24 11:20:22,41355,78.0,50,400600
9,ANN-6280,0,33,19,↗,60,219367,2665697,120.6987,24.0960,,2018-01-24 11:20:52,41472,196.0,60,400600
10,ANN-6280,0,36,100,→,60,219601,2665707,120.7010,24.0961,,2018-01-24 11:21:22,500409,234.0,60,400600
11,ANN-6280,0,26,18,↗,50,219815,2665762,120.7031,24.0966,,2018-01-24 11:21:52,301918,221.0,50,400600
12,ANN-6280,90,1,159,↘,50,219876,2665828,120.7037,24.0972,,2018-01-24 11:22:22,320637,90.0,50,400600
13,ANN-6280,91,0,227,↙,50,219876,2665828,120.7037,24.0972,,2018-01-24 11:22:37,320637,0.0,50,400600
14,ANN-6280,78,0,227,↙,50,219876,2665828,120.7037,24.0972,,2018-01-24 11:22:38,320637,0.0,50,400600
15,ANN-6280,0,23,192,↙,50,219866,2665762,120.7036,24.0966,,2018-01-24 11:22:52,320637,NaN,50,400600
16,ANN-6280,90,0,190,↓,50,219866,2665729,120.7036,24.0963,,2018-01-24 11:23:22,320637,100.0,50,400600
17,ANN-6280,0,21,190,↓,60,219855,2665684,120.7035,24.0959,,2018-01-24 11:23:52,500409,46.0,60,400600
18,ANN-6280,0,15,169,↘,50,219804,2665485,120.7030,24.0941,,2018-01-24 11:24:22,320637,205.0,50,400600
19,ANN-6280,0,13,227,↙,50,219855,2665396,120.7035,24.0933,,2018-01-24 11:24:52,301846,103.0,50,400600
20,ANN-6280,89,0,265,←,50,219804,2665397,120.7030,24.0933,,2018-01-24 11:25:22,-2987,51.0,50,400600
21,ANN-6280,89,0,265,←,50,219804,2665385,120.7030,24.0932,,2018-01-24 11:25:52,-2987,12.0,50,400600
22,ANN-6280,89,0,265,←,50,219804,2665385,120.7030,24.0932,,2018-01-24 11:26:22,-2987,NaN,50,400600
23,ANN-6280,68,0,265,←,50,219804,2665385,120.7030,24.0932,,2018-01-24 11:26:30,-2987,NaN,50,400600
24,ANN-6280,78,0,265,←,50,219804,2665385,120.7030,24.0932,,2018-01-24 11:26:31,-2987,0.0,50,400600
25,ANN-6280,0,8,298,↖,50,219784,2665397,120.7028,24.0933,,2018-01-24 11:26:52,320637,23.0,50,400600
26,ANN-6280,0,22,214,↙,50,219722,2665275,120.7022,24.0922,,2018-01-24 11:27:22,320637,137.0,50,400600
27,ANN-6280,90,0,137,↘,50,219773,2665208,120.7027,24.0916,,2018-01-24 11:27:52,320652,84.0,50,400600
28,ANN-6280,90,0,137,↘,50,219763,2665208,120.7026,24.0916,,2018-01-24 11:28:23,335948,10.0,50,400600
29,ANN-6280,90,0,137,↘,50,219763,2665197,120.7026,24.0915,,2018-01-24 11:28:53,335948,11.0,50,400600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,APM-6503,90,0,83,→,50,213607,2671325,120.6419,24.1467,,2018-01-24 16:00:44,319999,0.0,50,400583
9971,APM-6503,90,0,83,→,50,213607,2671325,120.6419,24.1467,,2018-01-24 16:01:14,319999,0.0,50,400583
9972,APM-6503,90,0,83,→,50,213617,2671325,120.6420,24.1467,,2018-01-24 16:01:45,319999,10.0,50,400583
9973,APM-6503,90,0,83,→,50,213617,2671336,120.6420,24.1468,,2018-01-24 16:02:15,319999,11.0,50,400583
9974,APM-6503,90,1,101,→,50,213617,2671325,120.6420,24.1467,,2018-01-24 16:02:45,319999,11.0,50,400583
9975,APM-6503,90,1,101,→,50,213617,2671314,120.6420,24.1466,,2018-01-24 16:03:15,319999,11.0,50,400583
9976,APM-6503,91,0,101,→,50,213627,2671314,120.6421,24.1466,,2018-01-24 16:03:37,319999,10.0,50,400583
9977,APM-6503,90,0,101,→,50,213637,2671314,120.6422,24.1466,,2018-01-24 16:03:45,319999,10.0,50,400583
9978,APM-6503,90,0,101,→,50,213637,2671314,120.6422,24.1466,,2018-01-24 16:04:15,319999,0.0,50,400583
9979,APM-6503,78,0,101,→,50,213637,2671314,120.6422,24.1466,,2018-01-24 16:06:49,319999,NaN,50,400583
9980,APM-6503,91,0,101,→,50,213637,2671314,120.6422,24.1466,,2018-01-24 16:06:50,319999,NaN,50,400583
9981,APM-6503,78,0,101,→,50,213637,2671314,120.6422,24.1466,,2018-01-24 16:06:51,319999,NaN,50,400583
9982,APM-6503,90,0,29,↗,50,213637,2671325,120.6422,24.1467,,2018-01-24 16:07:18,319999,11.0,50,400583
9983,APM-6503,0,7,93,→,50,213648,2671336,120.6423,24.1468,,2018-01-24 16:07:48,319999,16.0,50,400583
9984,APM-6503,90,0,93,→,50,213658,2671336,120.6424,24.1468,,2018-01-24 16:08:18,319999,10.0,50,400583
9985,APM-6503,0,12,94,→,50,213729,2671336,120.6431,24.1468,,2018-01-24 16:08:48,301142,71.0,50,400583
9986,APM-6503,0,30,194,↙,50,213769,2671192,120.6435,24.1455,,2018-01-24 16:09:18,301174,149.0,50,400583
9987,APM-6503,90,0,192,↙,50,213738,2671070,120.6432,24.1444,,2018-01-24 16:09:48,301174,126.0,50,400583
9988,APM-6503,90,0,182,↓,50,213728,2671037,120.6431,24.1441,,2018-01-24 16:10:18,301174,34.0,50,400583
9989,APM-6503,0,30,96,→,50,213942,2671003,120.6452,24.1438,,2018-01-24 16:10:48,301148,217.0,50,400583
9990,APM-6503,90,0,92,→,50,214043,2670992,120.6462,24.1437,,2018-01-24 16:11:18,301148,102.0,50,400583
9991,APM-6503,90,3,86,→,50,214196,2670991,120.6477,24.1437,,2018-01-24 16:11:48,319998,153.0,50,400583
9992,APM-6503,0,22,84,→,50,214226,2671124,120.6480,24.1449,,2018-01-24 16:12:18,319962,136.0,50,400583
9993,APM-6503,90,0,87,→,50,214287,2671124,120.6486,24.1449,,2018-01-24 16:12:48,319997,61.0,50,400583
9994,APM-6503,0,7,91,→,50,214298,2671124,120.6487,24.1449,,2018-01-24 16:13:18,319997,11.0,50,400583
9995,APM-6503,0,31,91,→,50,214491,2671124,120.6506,24.1449,,2018-01-24 16:13:48,319962,193.0,50,400583
9996,APM-6503,0,37,96,→,50,214796,2671123,120.6536,24.1449,,2018-01-24 16:14:18,320219,305.0,50,400583
9997,APM-6503,0,22,97,→,60,215060,2671111,120.6562,24.1448,,2018-01-24 16:14:48,359950,264.0,60,400583
9998,APM-6503,90,0,79,↗,50,215131,2671122,120.6569,24.1449,,2018-01-24 16:15:18,301330,72.0,50,400583
9999,APM-6503,90,0,79,↗,50,215141,2671122,120.6570,24.1449,,2018-01-24 16:15:48,301330,10.0,50,400583

In [29]:
df = pd.read_csv("./small_set/CC_B.csv", header=None, encoding="big5")

In [30]:
df

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,990326,9991231,4.0,11250.0,4.0,7.0,100146.0,100999.0,100146.0,0.0,...,00010100,NaN,0.0,0.0,0.0,0.0,990329,135510.0,0.0,0.0
1,961029,9991231,1.0,114.0,5.0,99.0,100151.0,100151.0,100151.0,0.0,...,11111100,NaN,0.0,0.0,0.0,0.0,970530,142824.0,0.0,0.0
2,1050505,9991231,1.0,241.0,99.0,99.0,241007.0,241999.0,241007.0,0.0,...,00110100,NaN,0.0,0.0,0.0,0.0,1050505,115904.0,0.0,0.0
3,990105,9991231,1.0,11677.0,5.0,99.0,100013.0,100999.0,100013.0,0.0,...,00000100,NaN,0.0,0.0,0.0,0.0,990105,164847.0,0.0,0.0
4,970303,9991231,2.0,61343.0,5.0,4.0,600047.0,600999.0,600047.0,1.0,...,00100000,NaN,0.0,0.0,0.0,0.0,980818,152805.0,0.0,0.0
5,970303,9991231,1.0,802.0,7.0,99.0,300047.0,300999.0,300047.0,1.0,...,11111100,NaN,0.0,0.0,0.0,0.0,990608,163417.0,0.0,0.0
6,1030701,9991231,1.0,70458.0,7.0,7.0,704011.0,704999.0,704011.0,0.0,...,10101000,NaN,0.0,0.0,0.0,0.0,1030701,145205.0,0.0,0.0
7,1000916,9991231,1.0,242.0,4.0,9.0,241048.0,241999.0,244148.0,0.0,...,10000000,NaN,0.0,0.0,0.0,0.0,1000916,140647.0,0.0,0.0
8,1050615,9991231,4.0,30046.0,9.0,6.0,300010.0,300999.0,300010.0,0.0,...,10101000,NaN,0.0,0.0,0.0,0.0,1050616,85502.0,0.0,0.0
9,1040128,9991231,1.0,30049.0,5.0,4.0,300014.0,300999.0,300014.0,0.0,...,11111100,NaN,0.0,0.0,0.0,0.0,1040129,82816.0,0.0,0.0
10,981225,9991231,4.0,40748.0,5.0,7.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85541.0,0.0,0.0
11,1050420,9991231,1.0,93145.0,99.0,99.0,900061.0,900999.0,900061.0,0.0,...,11111100,NaN,0.0,0.0,0.0,0.0,1050421,151433.0,0.0,0.0
12,990202,9991231,1.0,30074.0,7.0,9.0,300019.0,300999.0,300019.0,0.0,...,11111100,NaN,0.0,0.0,0.0,0.0,990202,155535.0,0.0,0.0
13,981225,9991231,4.0,11074.0,5.0,13.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85558.0,0.0,0.0
14,1011109,9991231,1.0,24156.0,5.0,9.0,241017.0,241999.0,241017.0,0.0,...,10111100,NaN,0.0,0.0,0.0,0.0,1011109,135728.0,0.0,0.0
15,981225,9991231,4.0,84043.0,5.0,7.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85614.0,0.0,0.0
16,990422,9991231,2.0,41201.0,4.0,7.0,400045.0,400999.0,400045.0,0.0,...,11111100,NaN,0.0,0.0,0.0,0.0,990422,140135.0,0.0,0.0
17,981225,9991231,2.0,62152.0,5.0,7.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85634.0,0.0,0.0
18,981225,9991231,2.0,64743.0,5.0,9.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85653.0,0.0,0.0
19,1020318,9991231,2.0,30078.0,8.0,6.0,300019.0,300999.0,300019.0,1.0,...,00001100,NaN,0.0,0.0,0.0,0.0,1020318,101649.0,0.0,0.0
20,981225,9991231,2.0,40460.0,5.0,9.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85715.0,0.0,0.0
21,981225,9991231,2.0,62248.0,5.0,9.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85731.0,0.0,0.0
22,981225,9991231,2.0,63345.0,5.0,9.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85748.0,0.0,0.0
23,990111,9991231,4.0,725.0,99.0,9.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85807.0,0.0,0.0
24,990111,9991231,4.0,40461.0,99.0,99.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85826.0,0.0,0.0
25,1040727,9991231,1.0,97059.0,99.0,99.0,970011.0,970999.0,970011.0,0.0,...,10101000,NaN,0.0,0.0,0.0,0.0,1040727,161627.0,0.0,0.0
26,990111,9991231,4.0,91252.0,99.0,7.0,730019.0,704999.0,730019.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,85855.0,0.0,0.0
27,980702,9991231,2.0,10077.0,5.0,12.0,100006.0,100999.0,100006.0,0.0,...,11111100,NaN,0.0,0.0,0.0,0.0,980706,143836.0,0.0,0.0
28,970818,9991231,1.0,10479.0,5.0,99.0,100071.0,100999.0,100071.0,0.0,...,11111100,NaN,0.0,0.0,0.0,0.0,970818,150536.0,0.0,0.0
29,990510,9991231,2.0,11060.0,5.0,99.0,100099.0,100999.0,100099.0,0.0,...,00000100,NaN,0.0,0.0,0.0,0.0,990510,111010.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46335,981229,9991231,2.0,62152.0,99.0,99.0,730016.0,704999.0,730016.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990107,150027.0,0.0,0.0
46336,981225,9991231,2.0,62152.0,5.0,9.0,730037.0,704999.0,730037.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,91915.0,0.0,0.0
46337,981230,9991231,2.0,62152.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141059.0,0.0,0.0
46338,981229,9991231,2.0,64743.0,99.0,9.0,730016.0,704999.0,730016.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990107,150044.0,0.0,0.0
46339,981225,9991231,2.0,64743.0,5.0,9.0,730037.0,704999.0,730037.0,0.0,...,00001100,NaN,0.0,0.0,0.0,0.0,1000714,91932.0,0.0,0.0
46340,981230,9991231,2.0,64743.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141124.0,0.0,0.0
46341,981229,9991231,2.0,40460.0,99.0,9.0,730016.0,704999.0,730016.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990107,150100.0,0.0,0.0
46342,981225,9991231,2.0,40460.0,5.0,9.0,730037.0,704999.0,730037.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,91946.0,0.0,0.0
46343,981230,9991231,2.0,40460.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141153.0,0.0,0.0
46344,981229,9991231,2.0,62248.0,99.0,99.0,730016.0,704999.0,730016.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990107,150114.0,0.0,0.0
46345,981225,9991231,2.0,62248.0,5.0,9.0,730037.0,704999.0,730037.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,92005.0,0.0,0.0
46346,981230,9991231,2.0,62248.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141217.0,0.0,0.0
46347,981229,9991231,2.0,63345.0,99.0,9.0,730016.0,704999.0,730016.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990107,150129.0,0.0,0.0
46348,981225,9991231,2.0,63345.0,5.0,9.0,730037.0,704999.0,730037.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000714,92018.0,0.0,0.0
46349,990108,9991231,2.0,725.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141249.0,0.0,0.0
46350,990923,9991231,2.0,40461.0,99.0,99.0,730001.0,704999.0,730001.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000715,83817.0,0.0,0.0
46351,990108,9991231,2.0,40461.0,99.0,9.0,730037.0,704999.0,730037.0,0.0,...,00001100,NaN,0.0,0.0,0.0,0.0,1000714,92031.0,0.0,0.0
46352,990111,9991231,4.0,40461.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141313.0,0.0,0.0
46353,990108,9991231,4.0,91252.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141331.0,0.0,0.0
46354,990420,9991231,4.0,736.0,99.0,9.0,730041.0,704999.0,730041.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000706,135119.0,0.0,0.0
46355,990419,9991231,4.0,736.0,99.0,9.0,730049.0,704999.0,730049.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990421,93554.0,0.0,0.0
46356,990416,9991231,4.0,736.0,5.0,9.0,730030.0,704999.0,730030.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990517,150151.0,0.0,0.0
46357,990513,9991231,4.0,721.0,99.0,7.0,730009.0,704999.0,730009.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990517,150205.0,0.0,0.0
46358,990513,9991231,4.0,73444.0,99.0,9.0,730009.0,704999.0,730009.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990517,150105.0,0.0,0.0
46359,990923,9991231,2.0,734.0,5.0,99.0,730009.0,704999.0,730009.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,1000622,143252.0,0.0,0.0
46360,990111,9991231,2.0,725.0,99.0,99.0,730011.0,704999.0,730011.0,0.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990809,141415.0,0.0,0.0
46361,990521,9991231,1.0,32748.0,5.0,9.0,320025.0,NaN,320025.0,0.0,...,10101000,NaN,0.0,0.0,0.0,NaN,990806,NaN,0.0,0.0
46362,990630,9991231,1.0,961.0,5.0,9.0,950021.0,950999.0,950021.0,1.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990630,160732.0,0.0,0.0
46363,990630,9991231,1.0,961.0,5.0,9.0,950021.0,950999.0,950021.0,1.0,...,00001000,NaN,0.0,0.0,0.0,0.0,990630,160241.0,0.0,0.0
46364,1060627,9991231,2.0,10041.0,5.0,12.0,100008.0,100999.0,100008.0,0.0,...,10111100,NaN,0.0,0.0,0.0,0.0,1070302,94616.0,0.0,0.0