!apt update; apt install p7zip-full
!wget http://bigdata.fychao.info/data/newTTS.7z
!7z x newTTS.7z
!ls -alh

In [15]:
!pip install joblib

Requirement already satisfied: joblib in /usr/local/lib/python3.5/dist-packages (0.11)
You are using pip version 19.0.2, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

# create samll dataset

In [5]:
!head -n 100000 newTTS1.csv > newTTS1_s.csv

In [6]:
!ls -alh

total 19G
drwxr-xr-x 3 root root 4.0K May 11 06:41 .
drwxr-xr-x 7 root root 4.0K May 11 05:43 ..
drwxr-xr-x 2 root root 4.0K May 11 05:43 .ipynb_checkpoints
-rw-r--r-- 1 root root 3.0K May 11 06:41 Untitled.ipynb
-rw-r--r-- 1 root root 2.1G May 11 05:42 newTTS.7z
-rw-r--r-- 1 root root  17G May 11 00:15 newTTS1.csv
-rw-r--r-- 1 root root 4.4M May 11 06:41 newTTS1_s.csv

In [3]:
import os
import re
from joblib import Parallel, delayed

In [4]:
all_mail = {}
all_mail_code = set()
with open("newTTS1_s.csv", 'r') as mfile:
    for line in mfile:
        (mail_code, status, post_code, mtime) = line.strip().split(",")

        if not mail_code in all_mail_code:
            all_mail_code.add(mail_code)
            all_mail[mail_code] = []

        all_mail[mail_code].append((status, post_code, mtime))

# node - edge

In [5]:
all_mail_code = list(all_mail_code )

In [6]:
for mail_code in all_mail_code[:3]:
    print(mail_code, all_mail[mail_code])

00007230301916 [('A1', '300019', '2018-01-02 17:34:00')]
85058200101970 [('A1', '360022', '2018-01-02 09:32:00')]
32302400101170 [('A1', '220002', '2018-01-02 11:38:00')]

In [10]:
def makeNodeEdge(mail_proc):
    results = []
    for idx in range(len(mail_proc)-1):
        (frm_status, frm_post_code, frm_mtime) = mail_proc[idx]
        (to_status, to_post_code, to_mtime) = mail_proc[idx+1]
        results.append( (frm_status, to_status, 
                         frm_post_code, to_post_code, 
                         frm_mtime, to_mtime) )
    return results
makeNodeEdge(all_mail["15778340102018"])

ValueError: time data '2018-01-02 15:42:00' does not match format '%Y:%m:%d %H:%M:%S'

In [19]:
all_edges = Parallel(n_jobs=-1)(delayed(makeNodeEdge)(all_mail[mail_code] ) for mail_code in all_mail_code)

In [24]:
print( all_edges[:3] ) # this is list of list

[[], [('Z2', 'G2', '704584', '704018', '2018-01-02 04:56:17', '2018-01-02 10:40:00')], [('A1', 'Z4', '400020', '400672', '2018-01-02 15:42:00', '2018-01-02 21:06:53')]]

In [25]:
flat_all_edges = [ y for x in all_edges for y in x]

In [26]:
flat_all_edges[:3]

[('Z2',
  'G2',
  '704584',
  '704018',
  '2018-01-02 04:56:17',
  '2018-01-02 10:40:00'),
 ('A1',
  'Z4',
  '400020',
  '400672',
  '2018-01-02 15:42:00',
  '2018-01-02 21:06:53'),
 ('Y7',
  'I7',
  '100572',
  '100572',
  '2018-01-02 10:31:43',
  '2018-01-02 13:58:29')]

In [27]:
import pandas as pd

In [28]:
df = pd.DataFrame(flat_all_edges)

In [30]:
df.columns = ["frm_status", "to_status", "frm_post_code", "to_post_code", "frm_mtime", "to_mtime"]

In [33]:
df['frm_mtime'] = pd.to_datetime(df['frm_mtime'])
df['to_mtime'] = pd.to_datetime(df['to_mtime'])

In [35]:
df['diff_mtime'] = df['to_mtime'] - df['frm_mtime']

In [44]:
df['frm_init'] = df['frm_status'].str.slice(0,1)
df['to_init'] = df['to_status'].str.slice(0,1)

In [50]:
df['frm_code'] = df['frm_post_code'] + "-" + df['frm_init']
df['to_code'] = df['to_post_code'] + "-" + df['to_init']

In [54]:
ndf = df[['frm_init', 'to_init', 'frm_code', 'to_code', 'diff_mtime']]

In [57]:
ndf.set_index(['frm_init', 'to_init'], inplace=True)

In [70]:
ndf.loc[('A', 'A')].diff_mtime.mean()

Timedelta('0 days 01:09:33.333333')

In [102]:
mean_time = []
for frm_scode in sorted(df.frm_init.unique()):
    for to_scode in sorted(df.to_init.unique()):
        if (frm_scode, to_scode) in ndf.index:
            mean_time.append ( ((frm_scode, to_scode), 
                   len(ndf.loc[(frm_scode, to_scode)]), 
                   ndf.loc[(frm_scode, to_scode)].diff_mtime.mean(),
                   ndf.loc[(frm_scode, to_scode)].diff_mtime.var()))

In [103]:
mean_df = pd.DataFrame(mean_time)

In [104]:
mean_df.columns = ['frm_to', 'cntr', 'mean', 'var']

In [105]:
mean_df.sort_values("cntr", ascending=False)

    frm_to   cntr                   mean           var
63  (Y, I)  25966 0 days 06:16:44.516174  2.163592e+26
5   (A, Z)   7996 0 days 06:02:09.093671  9.133730e+25
62  (Y, H)   4064 0 days 05:10:07.527312  3.026559e+25
77  (Z, Y)    799 0 days 02:44:59.385481  5.076295e+25
71  (Z, G)    718 0 days 04:15:08.837047  1.667067e+27
22  (H, Z)    554 0 days 03:40:42.234657  6.001645e+25
8   (G, I)    533 0 days 03:12:07.163227  1.787983e+27
21  (H, Y)    372 0 days 04:02:11.962365  4.262154e+25
45  (T, Z)    319 0 days 03:19:42.711598  8.813619e+25
61  (Y, G)    269 0 days 03:26:02.431226  7.973696e+26
39  (P, Y)    267 0 days 15:06:11.142322  1.208082e+28
78  (Z, Z)    250 0 days 06:58:56.644000  1.676431e+26
56  (X, H)    188 0 days 04:50:03.776595  1.304757e+27
54  (W, I)     96 0 days 10:00:47.072916  5.506629e+27
3   (A, V)     75 0 days 00:05:08.800000  1.330511e+24
26  (I, I)     71 0 days 02:48:39.239436  8.081091e+25
68  (Y, Y)     48 0 days 02:37:20.479166  2.032344e+27
16  (H, P)     47 0 days 03:12:11.638297  6.468410e+25
2   (A, P)     44 0 days 02:35:02.136363  5.229333e+25
40  (P, Z)     44 0 days 14:11:02.431818  1.118144e+28
19  (H, W)     38 0 days 01:22:26.131578  5.762586e+25
46  (V, A)     34 0 days 00:08:58.235294  3.570215e+24
57  (X, I)     30 0 days 08:18:28.933333  4.431700e+26
1   (A, I)     29 0 days 03:22:30.586206  5.251720e+25
15  (H, I)     29 0 days 02:19:23.965517  4.265062e+25
20  (H, X)     24 0 days 03:26:29.666666  6.592785e+25
60  (Y, A)     24 0 days 00:58:49.541666  3.944136e+24
36  (P, P)     21 0 days 06:14:26.523809  8.546597e+26
0   (A, A)     18 0 days 01:09:33.333333  2.036085e+25
14  (H, H)     16 0 days 02:11:40.125000  8.127351e+25
..     ...    ...                    ...           ...
64  (Y, P)      5 0 days 01:30:16.800000  9.521829e+25
48  (V, I)      5        0 days 02:04:40  8.103970e+25
33  (I, Z)      4 0 days 03:34:00.250000  2.580342e+23
27  (I, P)      4 0 days 02:51:50.500000  7.189277e+25
49  (V, P)      3 0 days 02:17:50.666666  6.391273e+25
38  (P, X)      3 0 days 03:55:00.333333  4.645217e+24
53  (W, H)      3 0 days 09:38:05.333333  3.489028e+27
37  (P, W)      3        0 days 11:50:44  3.100106e+25
76  (Z, X)      2 0 days 04:57:44.500000  3.338270e+26
10  (G, T)      2        1 days 11:53:54  3.337184e+28
70  (Z, A)      2 0 days 00:22:24.500000  1.445000e+20
67  (Y, X)      2        1 days 21:53:30  4.462220e+28
30  (I, W)      2 0 days 00:35:37.500000  4.301244e+24
51  (V, Y)      2 0 days 02:02:57.500000  1.066530e+26
23  (I, A)      1        0 days 00:30:06           NaN
18  (H, V)      1        0 days 01:52:45           NaN
43  (T, I)      1        0 days 03:34:12           NaN
75  (Z, W)      1        0 days 04:56:07           NaN
11  (G, Y)      1        0 days 00:30:00           NaN
41  (S, G)      1        0 days 00:36:48           NaN
72  (Z, H)      1        0 days 04:56:55           NaN
44  (T, T)      1        0 days 06:48:38           NaN
28  (I, T)      1        0 days 00:53:40           NaN
69  (Y, Z)      1        0 days 07:30:53           NaN
55  (X, A)      1        0 days 01:49:27           NaN
58  (X, V)      1        0 days 04:30:49           NaN
66  (Y, W)      1        0 days 01:37:35           NaN
31  (I, X)      1        0 days 00:41:05           NaN
7   (G, H)      1        0 days 02:00:25           NaN
12  (G, Z)      1        0 days 00:58:36           NaN

[79 rows x 4 columns]